### ISSUE TITLE
Number of timeframes

### ISSUE THREAD

**Issue by nicolasj92** [boschresearch/CNC_Machining#2]
In the README.md it says:
_Thereby normal as well as anomoulous data have been collected for 4 different timeframes, each lasting 5 months from February 2019 until August 2021 and labelled accordingly._

But aren't there 6 different timeframes within the dataset?

**Comment by MATnani** [comment]
Thank you very much for your comment. Indeed we have 6 different timeframes and I just adjusted the text in the README.md file. 

As highlighted in the paper [CIRP CMS](https://doi.org/10.1016/j.procir.2022.04.022) in section 3.1: "_The timeframe is tagged as ”Month_Year” and represents the 6-month interval before the label. For example, ”Aug_2019” would refer to the period between February 2019 and August 2019._"

Meaning:
1. Feb_2019 -> August 2018 - February 2019
2. Aug_2019 -> February 2019 - August 2019
3. Feb_2020 -> August 2019 - February 2020
4. Aug_2020 -> February 2020 - August 2020
5. Feb_2021 -> August 2020 - February 2021
6. Aug_2021 -> February 2021 - August 2021
