### ISSUE TITLE
Operation sequence and file naming

### ISSUE THREAD

**Issue by mariaclaraav** [boschresearch/CNC_Machining#5]
Hi, thanks for sharing this, but I have a few questions:

1.  Could you clarify how the order of operations (OP1, OP2, OP3) is executed on the workpieces? Specifically, does each machine perform OP1, then OP2, and finally OP3 on the same workpiece in sequence? Or does the machine complete OP1 on all workpieces before moving on to OP2, and so on?

2. The data is divided by machine, operation, and status, with file names formatted as {Machine}(Month){Year}{Operation Code}{Code}. However, the Code does not indicate the sequence of operations.

Is there additional information available that could be added to the dataset to provide this sequence? This information is crucial for working with continuous models to detect pattern changes before the first fault occurs. Currently, all the "anomalous" data is in sequence, causing a loss of the "time information" necessary for time series analysis.

**Comment by mariaclaraav** [comment]
Another issue concerns the window size. You recommend using 4096, but when I calculate the window size using the formula 
ws =Sampling rate/Rotational speed with a sampling rate of 2 kHz and a rotational speed of 250 Hz (which applies to most of our operations), I get a different value for the window size.

**Comment by MATnani** [comment]
Hi @mariaclaraav , 
thank you for your interest in our dataset. 

1. As explained in Section 3.1 of the paper, a machining process consists of a sequential combination of different operations (OPs). In Figure 4, an example of the machining process is provided, where the process is segmented, and each segment corresponds to an OP. This indicates that each machine performs OP1, OP2, and OP3 on the same workpiece in sequence; however, the operations do not necessarily follow a specific order. For confidentiality reasons, the order of the tool operations has been shuffled and anonymized. This means that OP2 does not necessarily follow OP1, and the operations can occur in any sequence.
2. The samples are named using the following format: {Machine}(Month){Year}{Operation Code}{Number of sample}. We collected multiple samples from different process runs, designated as Mx_OPy (where Mx represents machine x and OPy represents process ID y). These samples have been numbered sequentially using the {Number of sample}.
3. you are right. The window size is set to cover at least one full revolution of the motor. So using the formula we get that we can capture a full revolution with 8 samples. However, in our work the ws parameter has been tuned in a big range and the best result was given by ws=4096.
